(dotimes (i 100)
  (let ((num (+ i 1)))
    (if (= 0 (mod num 3))
      (prin1 "Fizz")
      nil)
    (if (= 0 (mod num 5))
      (prin1 "Buzz")
      nil)
    (if (and (not (= 0 (mod num 5)))
             (not (= 0 (mod num 3))))
      (prin1 num))
    (prin1 "\n")))
