(dotimes (i 100)
  (let ((num (+ i 1)))
    (if (= 0 (mod num 3))
      (princ "Fizz")
      nil)
    (if (= 0 (mod num 5))
      (princ "Buzz")
      nil)
    (if (and (not (= 0 (mod num 5)))
             (not (= 0 (mod num 3))))
      (print num))
    (print "\n")))
