(setq x 10)
(print x)
(setq x 20)
(print x)
(setq x '(a b))
(print x)

(setq x 10)
(let ((x 20)) (setq x 30) (print x))
(print x)

(setq a 1)
(defun x (a) (print a) (setq a 2) (print a))
(print a)
(x 10)
(print a)

(setq a 1)
(defun x (a) (print a) (lambda (b) (setq a (+ a b)) (print a)))
(print a)
(setq y (x 10))
(setq z (x 20))
(print a)
(funcall y 100)
(funcall z 1000)
(print a)
(funcall y 200)
(funcall z 2000)
(print a)

(print (setq))

(print (setq x1 (+ 10 20) x2 (* 30 40)))
(print x1)
(print x2)
