(print (type-of 1))
(print (type-of 1.2))
(print (type-of "fo"))
(print (type-of t))
(print (type-of nil))
(print (type-of 'a))
(print (type-of '1))
(print (type-of '1.2))
(print (type-of '"fo"))
(print (type-of 't))
(print (type-of 'nil))
(print (type-of ''a))
(print (type-of '(10 20)))
(print (type-of (lambda (x) x)))
