(setq x '(1 2 3 4 5))
(print x)
(setq y (cdr x))
(print y)
(print (rplacd y 10))
(print x)
(print (rplacd '(1 . 2) 3))
(print (rplacd '((1 2 3) (4 5 6)) '((7 8 9))))
(print (rplacd '(nil) 1))
(print (rplacd '(1) nil))
(print (rplacd '((1) 2) 3))
(print (rplacd '((1) 2) '(3)))
(print (rplacd '(1 (2)) 3))
(print (rplacd '(1 (2)) '(3)))
(print (rplacd '(1 (2)) nil))
(print (rplacd '(1 2) nil))
(print (rplacd '(1 . 2) '(3 4 5)))
(setq x '(1 2))
(print (apply 'rplacd `(,x (+ 3 4))))
