(print (cond))
(print (cond (nil)))
(print (cond (t)))
(print (cond (t 10)))
(cond (t (print 1) (print 2)))
(defun x (x)
  (cond ((= x 1) (print "one"))
        ((= x 2) (print "two"))
        (t (print "many"))))
(x 1)
(x 2)
(x 3)
