(print (consp nil))
(print (consp t))
(print (consp '(1 . 2)))
(print (consp '(1 2)))
(print (consp 1))
(print (consp 1.0))
(print (consp "string"))
(print (consp 'x))
(print (consp ''x))
(print (consp '`x))
(print (consp (lambda (x) x)))
(setq x '(+ 1 2))
(print (consp x))
(print (apply 'consp '((+ 1 2))))
